### ISSUE TITLE
Can't run script on raspberry pi

### ISSUE THREAD

**Issue by gabbello** [huxuan/iptv-m3u-filter#2]
When I try to run the script I get:
`pi@raspberrypi2:~/.local/bin $ ./iptv-filter 
Traceback (most recent call last):
  File "./iptv-filter", line 7, in <module>
    from iptvtools.iptv_filter import main
  File "/home/pi/.local/lib/python3.5/site-packages/iptvtools/iptv_filter.py", line 14, in <module>
    from .constants import helps
  File "/home/pi/.local/lib/python3.5/site-packages/iptvtools/constants/helps.py", line 12
    f'Configuration file to unify title and id information, defaults to '
                                                                        ^
SyntaxError: invalid syntax
`

**Comment by huxuan** [comment]
@gabbello Seems the [Literal String Interpolation](https://www.python.org/dev/peps/pep-0498/) is only supported after Python 3.6, will it be easy to upgrade Python on raspberry pi?

**Comment by gabbello** [comment]
Looks like I need to build it myself, which probably would take quite some time.

**Comment by huxuan** [comment]
Since Python 3.5 is released 5 years ago and will reach the end of life in less than one year [1]. I am not going to support it then. I would suggest to upgrade to Python 3.6 or even newer version.

I will close this is issue, if you still have any concern, please feel free to leave comments or even reopen it again.

[1] https://devguide.python.org/#status-of-python-branches

**Comment by gabbello** [comment]
ok, thank you. Just to let you know it works fine with 3.6

**Comment by huxuan** [comment]
@gabbello Thanks for the feedback! IPTVTools is still at an early stage. Any suggestions or comments are welcome!
